channels:
- conda-forge
dependencies:
- python=3.10.7
- pip<=25.1.1
- pip:
  - dagshub==0.5.10
  - cloudpickle==3.1.0
  - mlflow==2.19.0
  - matplotlib==3.10.3
  - numpy==2.2.1
  - pandas==2.3.0
  - seaborn==0.13.2
  - scikit-learn==1.7.0
  - scipy==1.15.3
name: mlflow-env